### ISSUE TITLE
Not able to pass request into the test function

### ISSUE THREAD

**Issue by thomasholknielsen** [NeuroCode-io/k8s-graceful-shutdown#54]
Thanks for a great library! :)

Would it be possible to extend the functionality to pass the req into the test function? 

Among other things, this would allow you to use the req.app.local.variable syntax to access variables within the test function.

Regards 
Thomas

**Comment by donchev7** [comment]
Hi Thomas,

We can do this. You will however need to overwrite the types for the **req** object. We use **IncomingMessage**  because we tried to keep this library generic and not express specific.

Would that work for you?

**Comment by donchev7** [comment]
I added the req object as an optional parameter to the test function in release [1.4.0](https://github.com/neurocode-io/k8s-graceful-shutdown/releases/tag/v1.4.0)
