### ISSUE TITLE
Question about the need of readiness probe in 500

### ISSUE THREAD

**Issue by jodem** [NeuroCode-io/k8s-graceful-shutdown#98]
Hello,

I have been testing the lib on k8 deployments. I have one question about the need to return a 5xx to the readiness route.

In my test I noticed k8 was removing the pod from the service as soon as the termination request was sent to the container, it looks it's not waiting for the readiness probe to fail twice.

The lib remains useful to register hooks to be called upon termination signal but I wonder if it's still relevant to manage the readiness probe 5xx when termination was requested.

PS : It would be great to have a version without KOA in the d.ts for people that only use express

Thanks

**Comment by donchev7** [comment]
Hi, I think you are referring to https://github.com/neurocode-io/k8s-graceful-shutdown/blob/main/lib/k8s-graceful-shutdown.ts#L83

Once we receive a termination signal we start returning a 500 from the health endpoint.

I need to conduct my own tests on recent k8s versions to verify if this is indeed not needed anymore. Can you tell me what version of k8s you tested on?

With regards to KOA. We actually do not dependent on any NPM packages. It's just the types. Not sure why the extra type is bothering you.

**Comment by jodem** [comment]
Hi, I did the test in k8 1.23

**Comment by donchev7** [comment]
I did some tests on both 1.23 and 1.24 and can confirm that k8s removes the pod from the service when the termination signal arrives.

I think its still beneficial to register a health test and return a 500 when the health test fails just so k8s can deregister the pod from the service. 

In future releases I'll probably remove this line https://github.com/neurocode-io/k8s-graceful-shutdown/blob/main/lib/k8s-graceful-shutdown.ts#L83
as k8s takes care of it now.

**Comment by donchev7** [comment]
https://github.com/neurocode-io/k8s-graceful-shutdown/commit/395446ef107c37dc6d42aa45fa2e5e93efaa974c

Now we don't return a 500 in the health test once a signal arrives since k8s removes the pod from the service anyway
